LOAD DATA LOCAL INFILE "room.csv"
INTO TABLE Room
FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "user.csv"
INTO TABLE User
FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "userDepartment.csv"
INTO TABLE UserDepartment
FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "event.dat"
INTO TABLE Event
FIELDS TERMINATED BY "<>";
